stages:
  - build
  - test
  - sast
  - deploy

variables:
  NODE_ENV: "production"
  DOCKER_IMAGE: "nextjs-app"
  SONAR_HOST_URL: "http://sonarqube:9000"
  SONAR_PROJECT_KEY: "nextjs-app"
  SONAR_TOKEN: $SONARQUBE_TOKEN

before_script:
  - export PATH=$PATH:/usr/local/bin

build:
  tags:
    - factory-monitoring-client
  stage: build
  script:
    - echo "Building Docker image..."
    - cp /home/sysadm/factory-monitoring-client/certs/certificate.crt certs/certificate.crt
    - cp /home/sysadm/factory-monitoring-client/certs/certificate.key certs/certificate.key
    - docker build --build-arg NEXT_PUBLIC_API_HOST=http://localhost:8080/api/v1 -t $DOCKER_IMAGE .
  artifacts:
    paths:
      - out/

test:
  tags:
    - factory-monitoring-client
  stage: test
  script:
    - echo "Running tests..."
    - docker run --rm $DOCKER_IMAGE npm test

sast:
  tags:
    - factory-monitoring-client
  stage: sast
  before_script:
    - cd factory-monitoring-client
  script:
    - sonar-scanner -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.projectKey=factory-monitoring-client -Dsonar.login=$SONAR_TOKEN
  allow_failure: true

deploy:
  tags:
    - factory-monitoring-client
  stage: deploy
  only:
    - main
  script:
    - echo "Deploying application..."
    - docker-compose down
    - docker-compose up -d --build
