version: '3.8'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_HOST: http://localhost:8080/api/v1
    container_name: nextjs-app
    ports:
      - "80:80"
      - "443:443"
    environment:
      NEXT_PUBLIC_API_HOST: http://localhost:8080/api/v1
    volumes:
      - ./certs:/etc/nginx/certs
    networks:
      - app-net

networks:
  app-net:
    driver: bridge