import { askpReport } from "@/components/shared/askp/columns"

export const testData: askpReport[] = [
    {
      id: 1,
      product: {
        id: 101,
        unitType: "Фасованная",
        type: "Алкогольная продукция",
        fullName: "Водка Кристалл",
        shortName: "Кристалл",
        alcCode: "123456789",
        capacity: 0.5,
        alcVolume: 0.4,
        productVCode: "ABC123",
        crotonaldehyde: 0.01,
        toluene: 0.005,
      },
      controlDate: new Date('2024-09-23T10:00:00'),
      vbsControl: 15.0,
      aControl: 300,
      percentAlc: 40.0,
      bottleCountControl: 50,
      temperature: 18.5,
      mode: "Отгрузка (покупателю)"
    },
    {
      id: 2,
      product: {
        id: 102,
        unitType: "Нефасованная",
        type: "Спиртосодержащая пищевая продукция",
        fullName: "Спирт",
        shortName: "Спирт",
        alcCode: "987654321",
        capacity: 1.0,
        alcVolume: 0.96,
        productVCode: "DEF456",
        crotonaldehyde: 0.02,
        toluene: 0.003,
      },
      controlDate: new Date('2024-09-24T11:30:00'),
      vbsControl: 25.0,
      aControl: 500,
      percentAlc: 96.0,
      bottleCountControl: 200,
      temperature: 20.0,
      mode: "Производство продукции"
    },
    {
      id: 3,
      product: {
        id: 103,
        unitType: "Фасованная",
        type: "Спиртосодержащая непищевая продукция",
        fullName: "Дезинфекционное средство",
        shortName: "Дезинфекция",
        alcCode: "135792468",
        capacity: 0.75,
        alcVolume: 0.7,
        productVCode: "GHI789",
        crotonaldehyde: 0.015,
        toluene: 0.002,
      },
      controlDate: new Date('2024-09-25T14:00:00'),
      vbsControl: 30.0,
      aControl: 600,
      percentAlc: 70.0,
      bottleCountControl: 150,
      temperature: 22.0,
      mode: "Калибровка АСИиУ"
    },
    {
      id: 4,
      product: {
        id: 104,
        unitType: "Нефасованная",
        type: "Этиловый спирт",
        fullName: "Этиловый спирт 96%",
        shortName: "Этил 96%",
        alcCode: "246813579",
        capacity: 5.0,
        alcVolume: 4.8,
        productVCode: "JKL012",
        crotonaldehyde: 0.03,
        toluene: 0.007,
      },
      controlDate: new Date('2024-09-26T09:45:00'),
      vbsControl: 10.5,
      aControl: 250,
      percentAlc: 96.0,
      bottleCountControl: 75,
      temperature: 21.5,
      mode: "Промывка АСИиУ"
    },
    {
      id: 5,
      product: {
        id: 105,
        unitType: "Фасованная",
        type: "Алкогольная продукция",
        fullName: "Пиво Лагер",
        shortName: "Лагер",
        alcCode: "369258147",
        capacity: 0.33,
        alcVolume: 0.05,
        productVCode: "MNO345",
        crotonaldehyde: 0.008,
        toluene: 0.001,
      },
      controlDate: new Date('2024-09-27T16:20:00'),
      vbsControl: 5.0,
      aControl: 120,
      percentAlc: 5.0,
      bottleCountControl: 100,
      temperature: 19.0,
      mode: "Остановка АСИиУ"
    },
    {
      id: 6,
      product: {
        id: 106,
        unitType: "Нефасованная",
        type: "Спиртосодержащая пищевая продукция",
        fullName: "Настойка",
        shortName: "Настойка",
        alcCode: "159753486",
        capacity: 0.7,
        alcVolume: 0.45,
        productVCode: "PQR678",
        crotonaldehyde: 0.012,
        toluene: 0.006,
      },
      controlDate: new Date('2024-09-28T13:10:00'),
      vbsControl: 20.0,
      aControl: 400,
      percentAlc: 40.0,
      bottleCountControl: 80,
      temperature: 23.0,
      mode: "Прием (возврат)"
    },
    {
      id: 7,
      product: {
        id: 107,
        unitType: "Фасованная",
        type: "Спиртосодержащая непищевая продукция",
        fullName: "Ароматизатор",
        shortName: "Ароматизатор",
        alcCode: "321654987",
        capacity: 0.25,
        alcVolume: 0.2,
        productVCode: "STU901",
        crotonaldehyde: 0.004,
        toluene: 0.001,
      },
      controlDate: new Date('2024-09-29T08:30:00'),
      vbsControl: 12.5,
      aControl: 250,
      percentAlc: 80.0,
      bottleCountControl: 60,
      temperature: 20.5,
      mode: "Внутреннее перемещение"
    },
    {
      id: 8,
      product: {
        id: 108,
        unitType: "Нефасованная",
        type: "Этиловый спирт",
        fullName: "Этиловый спирт 70%",
        shortName: "Этил 70%",
        alcCode: "987123654",
        capacity: 1.5,
        alcVolume: 1.05,
        productVCode: "VWX234",
        crotonaldehyde: 0.016,
        toluene: 0.002,
      },
      controlDate: new Date('2024-09-30T07:15:00'),
      vbsControl: 40.0,
      aControl: 800,
      percentAlc: 70.0,
      bottleCountControl: 200,
      temperature: 21.0,
      mode: "Прием (закупка)"
    },
    {
      id: 9,
      product: {
        id: 109,
        unitType: "Фасованная",
        type: "Алкогольная продукция",
        fullName: "Коньяк",
        shortName: "Коньяк",
        alcCode: "456789123",
        capacity: 0.7,
        alcVolume: 0.6,
        productVCode: "YZA567",
        crotonaldehyde: 0.02,
        toluene: 0.004,
      },
      controlDate: new Date('2024-10-01T15:45:00'),
      vbsControl: 10.0,
      aControl: 250,
      percentAlc: 40.0,
      bottleCountControl: 100,
      temperature: 18.0,
      mode: "Отгрузка (возврат)"
    },
    {
      id: 10,
      product: {
        id: 110,
        unitType: "Нефасованная",
        type: "Спиртосодержащая пищевая продукция",
        fullName: "Энергетик",
        shortName: "Энергетик",
        alcCode: "147258369",
        capacity: 1.0,
        alcVolume: 0.9,
        productVCode: "BCD789",
        crotonaldehyde: 0.022,
        toluene: 0.003,
      },
      controlDate: new Date('2024-10-02T11:30:00'),
      vbsControl: 30.0,
      aControl: 600,
      percentAlc: 90.0,
      bottleCountControl: 120,
      temperature: 22.5,
      mode: "Производство продукции"
    },
    {
      id: 11,
      product: {
        id: 111,
        unitType: "Фасованная",
        type: "Алкогольная продукция",
        fullName: "Ром",
        shortName: "Ром",
        alcCode: "258369147",
        capacity: 0.5,
        alcVolume: 0.4,
        productVCode: "EFG345",
        crotonaldehyde: 0.017,
        toluene: 0.002,
      },
      controlDate: new Date('2024-10-03T10:00:00'),
      vbsControl: 15.0,
      aControl: 300,
      percentAlc: 40.0,
      bottleCountControl: 60,
      temperature: 19.0,
      mode: "Калибровка АСИиУ"
    },
    {
      id: 12,
      product: {
        id: 112,
        unitType: "Нефасованная",
        type: "Спиртосодержащая непищевая продукция",
        fullName: "Лак",
        shortName: "Лак",
        alcCode: "369147258",
        capacity: 2.0,
        alcVolume: 1.5,
        productVCode: "HJK678",
        crotonaldehyde: 0.019,
        toluene: 0.008,
      },
      controlDate: new Date('2024-10-04T13:30:00'),
      vbsControl: 20.0,
      aControl: 450,
      percentAlc: 75.0,
      bottleCountControl: 90,
      temperature: 24.0,
      mode: "Остановка АСИиУ"
    },
    {
      id: 13,
      product: {
        id: 113,
        unitType: "Фасованная",
        type: "Спиртосодержащая пищевая продукция",
        fullName: "Шампанское",
        shortName: "Шампанское",
        alcCode: "741258963",
        capacity: 0.75,
        alcVolume: 0.5,
        productVCode: "LMN012",
        crotonaldehyde: 0.009,
        toluene: 0.002,
      },
      controlDate: new Date('2024-10-05T09:00:00'),
      vbsControl: 12.0,
      aControl: 250,
      percentAlc: 30.0,
      bottleCountControl: 100,
      temperature: 21.0,
      mode: "Прием (возврат)"
    },
    {
      id: 14,
      product: {
        id: 114,
        unitType: "Нефасованная",
        type: "Этиловый спирт",
        fullName: "Этиловый спирт 50%",
        shortName: "Этил 50%",
        alcCode: "123987456",
        capacity: 1.0,
        alcVolume: 0.5,
        productVCode: "QRS345",
        crotonaldehyde: 0.014,
        toluene: 0.004,
      },
      controlDate: new Date('2024-10-06T08:45:00'),
      vbsControl: 18.0,
      aControl: 350,
      percentAlc: 50.0,
      bottleCountControl: 80,
      temperature: 22.0,
      mode: "Прием (закупка)"
    },
    {
      id: 15,
      product: {
        id: 115,
        unitType: "Фасованная",
        type: "Алкогольная продукция",
        fullName: "Вино",
        shortName: "Вино",
        alcCode: "654321789",
        capacity: 0.75,
        alcVolume: 0.6,
        productVCode: "TUV678",
        crotonaldehyde: 0.018,
        toluene: 0.005,
      },
      controlDate: new Date('2024-10-07T10:00:00'),
      vbsControl: 22.0,
      aControl: 500,
      percentAlc: 12.0,
      bottleCountControl: 110,
      temperature: 19.5,
      mode: "Технологический прогон"
    },
  ];