export const testData = [
    {
      id: 1,
      organization: "Организация А",
      govnumber: "A123BC",
      fullName: "Иван Иванов",
      line: "Линия 1",
      startDate: new Date(2024, 0, 1),
      endDate: new Date(2024, 0, 31),
      aqueousAlcohol: 100,
      anhydrousAlcohol: 95,
      alcoholStrength: 40,
      utmStatus: "Активен",
      rarStatus: "Проверен",
      product: {
        id: 101,
        temperature: "20°C",
        density: 0.789,
        strength: 40,
        deltaAqueousAlcohol: 0.2,
        deltaAnhydrousAlcohol: 0.15,
      },
    },
    {
      id: 2,
      organization: "Организация Б",
      govnumber: "B456DE",
      fullName: "Пётр Петров",
      line: "Линия 2",
      startDate: new Date(2024, 1, 10),
      endDate: new Date(2024, 1, 28),
      aqueousAlcohol: 110,
      anhydrousAlcohol: 100,
      alcoholStrength: 45,
      utmStatus: "Неактивен",
      rarStatus: "Не проверен",
      product: {
        id: 102,
        temperature: "18°C",
        density: 0.790,
        strength: 45,
        deltaAqueousAlcohol: 0.25,
        deltaAnhydrousAlcohol: 0.18,
      },
    },
    {
      id: 3,
      organization: "Организация В",
      govnumber: "C789FG",
      fullName: "Сергей Сергеев",
      line: "Линия 3",
      startDate: new Date(2024, 2, 5),
      endDate: new Date(2024, 2, 25),
      aqueousAlcohol: 120,
      anhydrousAlcohol: 110,
      alcoholStrength: 50,
      utmStatus: "Активен",
      rarStatus: "Проверен",
      product: {
        id: 103,
        temperature: "22°C",
        density: 0.792,
        strength: 50,
        deltaAqueousAlcohol: 0.3,
        deltaAnhydrousAlcohol: 0.2,
      },
    },
    {
      id: 4,
      organization: "Организация Г",
      govnumber: "D012HI",
      fullName: "Алексей Алексеев",
      line: "Линия 4",
      startDate: new Date(2024, 3, 15),
      endDate: new Date(2024, 3, 30),
      aqueousAlcohol: 105,
      anhydrousAlcohol: 97,
      alcoholStrength: 43,
      utmStatus: "Активен",
      rarStatus: "На проверке",
      product: {
        id: 104,
        temperature: "19°C",
        density: 0.788,
        strength: 43,
        deltaAqueousAlcohol: 0.22,
        deltaAnhydrousAlcohol: 0.16,
      },
    },
    {
      id: 5,
      organization: "Организация Д",
      govnumber: "E345JK",
      fullName: "Максим Максимов",
      line: "Линия 5",
      startDate: new Date(2024, 4, 10),
      endDate: new Date(2024, 4, 29),
      aqueousAlcohol: 115,
      anhydrousAlcohol: 105,
      alcoholStrength: 48,
      utmStatus: "Неактивен",
      rarStatus: "Проверен",
      product: {
        id: 105,
        temperature: "21°C",
        density: 0.791,
        strength: 48,
        deltaAqueousAlcohol: 0.28,
        deltaAnhydrousAlcohol: 0.19,
      },
    },
  ];
  